name: Deploy Service with SSH

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Copying files and artifacts via SSH
      - name: Copying service files and data to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.YANDEXCLOUD_IP }}
          username: "wccadmin"
          key: ${{ secrets.YANDEXCLOUD_SSH }}
          rm: true
          source: "service/"
          target: "/home/wccadmin/"
